// generated by stringer -type ItemType; DO NOT EDIT

package main

import "fmt"

const _ItemType_name = "CheckItemProjectItemDoneItemFilterItemPlaceholderItemPlaceholderDoneItemDeletedItem"

var _ItemType_index = [...]uint8{0, 9, 20, 28, 38, 53, 72, 83}

func (i ItemType) String() string {
	i -= 1
	if i < 0 || i+1 >= ItemType(len(_ItemType_index)) {
		return fmt.Sprintf("ItemType(%d)", i+1)
	}
	return _ItemType_name[_ItemType_index[i]:_ItemType_index[i+1]]
}
