// generated by stringer -type RepeatType; DO NOT EDIT

package main

import "fmt"

const _RepeatType_name = "DailyWeeklyMonthlyYearly"

var _RepeatType_index = [...]uint8{0, 5, 11, 18, 24}

func (i RepeatType) String() string {
	i -= 1
	if i < 0 || i+1 >= RepeatType(len(_RepeatType_index)) {
		return fmt.Sprintf("RepeatType(%d)", i+1)
	}
	return _RepeatType_name[_RepeatType_index[i]:_RepeatType_index[i+1]]
}
